######################################

# This script:
# processes data and applies eligibility criteria  
# arguments: stage, match_round
# - stage = treated, potentialcontrol or actualcontrol
# - match_round only required when stage = potentialcontrol or actualcontrol
######################################

# Preliminaries ----

## Import libraries ----
library(tidyverse)
library(lubridate)
library(glue)
library(here)

## import local functions and parameters ---

source(here("analysis", "design.R"))

source(here("lib", "functions", "utility.R"))

source(here("analysis", "process", "process_functions.R"))

## import command-line arguments ----

args <- commandArgs(trailingOnly = TRUE)

if (length(args) == 0) {
  # use for interactive testing
  # stage <- "treated"
  stage <- "controlpotential"
  # stage <- "controlactual"
  match_strategy <- "none"
  match_round <- as.integer("1")
} else {
  stage <- args[[1]]
  if (stage %in% c("controlpotential", "controlactual")) {
    match_strategy <- args[[2]]
    match_round <- as.integer(args[[3]])
  }
} 

# ## create output directories and define parameters ----
if (stage == "treated") {
  path_stem <- here("output", "treated")
  fs::dir_create(file.path(path_stem, "flowchart"))
  fs::dir_create(here("output", "report"))
  custom_path <- file.path(path_stem, "dummydata", "dummydata_treated.feather")
} else if (stage %in% c("controlpotential", "controlactual")) {
  path_stem <- ghere("output", "incremental_{match_strategy}", "matchround{match_round}", stage)
  fs::dir_create(file.path(path_stem, "match"))
  custom_path <- here("output", "incremental_none", "matchround1", "controlpotential", "dummydata", "dummydata_controlpotential.feather")
  match_round_date <- study_dates$control_extract[match_round]
}
fs::dir_create(file.path(path_stem, "eligible"))
fs::dir_create(file.path(path_stem, "process"))


# import data ----

# read data generated by study def
data_studydef <- arrow::read_feather(
  file.path(path_stem, "extract", glue("input_{stage}.feather"))
) %>%
  process_input()

if (stage == "controlactual") {
  
  ## trial info for potential matches in round X
  data_potential_matchstatus <- 
    read_rds(
      ghere("output", "incremental_{match_strategy}", "matchround{match_round}", "controlpotential", "match", "data_potential_matchstatus.rds")
      ) %>% 
    filter(matched==1L)
  
}

if(Sys.getenv("OPENSAFELY_BACKEND") %in% c("", "expectations")) {
  
  data_dummy <- arrow::read_feather(custom_path) 
  
  if (stage == "controlpotential") {
    data_dummy <- data_dummy %>%
      mutate(matchroundindex_date = match_round_date)
  }
  
  # extra processing if stage=controlactual
  if (stage == "controlactual") {
    
    # set seed so that dummy data results are reproducible
    set.seed(10)
    
    # reuse previous extraction for dummy run, dummy_control_potential1.feather
    data_dummy <- data_dummy %>%
      filter(patient_id %in% data_potential_matchstatus[(data_potential_matchstatus$treated==0L),]$patient_id) %>%
      # trial_date and match_id are not included in the dummy data so join them on here
      # they're joined in the study def using `with_values_from_file`
      left_join(
        data_potential_matchstatus %>% 
          filter(treated==0L) %>%
          select(patient_id, trial_date, match_id),
        by="patient_id"
      ) %>%
      # change a few variables so some matches fail
      mutate(
        region = if_else(runif(n())<0.05, sample(x=unique(region), size=n(), replace=TRUE), region)
      )
    
  }
  
  # check cutom and studydef dummydata match
  source(here("analysis", "dummydata", "dummydata_check.R"))
  dummydata_check(
    dummydata_studydef= data_studydef,
    dummydata_custom = data_dummy
  )
  
  data_extract <- data_dummy
  rm(data_dummy)
  
} else {
  
  data_extract <- data_studydef
  
}

rm(data_studydef)

# add certain match variables
if (stage == "controlactual") {
  
  # add: treated 
  data_extract <- data_extract %>%
    mutate(treated=0L) %>%
    # add: trial_time, matched, control, controlistreated_date to data_extract
    left_join(
      data_potential_matchstatus %>%
        filter(treated==0L),
      by=c("patient_id", "treated", "trial_date", "match_id")
    )
  
}
    
# summarise extracted data 
my_skim(data_extract, path = file.path(path_stem, "extract", glue("input_{stage}_skim.txt")))

cat("check for dates that are '1900-01-01', as this may indicate missing:\n")
data_extract %>%
  select(where(is.Date)) %>%
  pivot_longer(cols = everything()) %>%
  filter(!is.na(value), value == "1900-01-01") %>%
  group_by(name) %>%
  count()

# process data -----

# define index_date depending on stage
stage_index_date <- list(
  treated = "vax_boostautumn_date",
  controlpotential = "match_round_date",
  controlactual = "trial_date"
)

# process variables
data_processed <- data_extract %>%
  mutate(index_date = !! sym(stage_index_date[[stage]]), .after=1) %>%
  # process jcvi variables
  mutate(
    
    # number of conditions in different organ systems
    multimorb = sev_obesity + chronic_heart_disease + chronic_kidney_disease +
      diabetes + chronic_liver_disease + chronic_resp_disease + 
      chronic_neuro_disease,
    multimorb = cut(
      multimorb,
      breaks = c(0, 1, 2, Inf), 
      labels=c("0", "1", "2+"),
      right=FALSE
      ),
    
    # include asplenia in definition of immunosuppressed
    immunosuppressed = immunosuppressed | asplenia,
    
    # clinically at-risk group
    cv = immunosuppressed | chronic_kidney_disease | chronic_resp_disease | 
      diabetes | chronic_liver_disease | chronic_neuro_disease | 
      chronic_heart_disease | learndis | sev_mental | sev_obesity,
    
    # these are the agegroups by which people were eligible to book vaccine doses
    # note that technically those aged both 65-74 and 75+ could receive from 12 Sept,
    # but those aged 75+ could book from 7 Sept, whereas 65-74 could only book from 12 Sept
    agegroup_match = cut(
      age,
      breaks=c(50, 65, 75, Inf),
      labels=c("50-64", "65-74", "75+"),
      right=FALSE
    ),
    
  )  %>%
  # process demographics
  mutate(
    
    sex = fct_case_when(
      sex == "F" ~ "Female",
      sex == "M" ~ "Male",
      TRUE ~ NA_character_
    ),
    
    ethnicity = factor(
      ethnicity,
      levels = c("White", "Mixed", "Asian or Asian British", "Black or Black British", "Other")
    ),
    
    region = fct_collapse(
      region,
      `East of England` = "East",
      `London` = "London",
      `Midlands` = c("West Midlands", "East Midlands"),
      `North East and Yorkshire` = c("Yorkshire and The Humber", "North East"),
      `North West` = "North West",
      `South East` = "South East",
      `South West` = "South West"
    ),
    
    imd_Q5 = factor(
      imd_Q5,
      levels = c("1 (most deprived)", "2", "3", "4", "5 (least deprived)")
    )
    
  ) %>%
  # process pre-baseline events
  mutate(
    timesincecoviddischarged = as.integer(index_date - discharged_covid_0_date),
    timesincecoviddischarged = fct_case_when(
      is.na(timesincecoviddischarged) ~ "No prior COVID-19 admission",
      timesincecoviddischarged > 180 ~ "181+ days",
      timesincecoviddischarged <= 180 ~ "31-180 days",
      timesincecoviddischarged <= 30 ~ "1-30 days", # will be excluded
      timesincecoviddischarged <= 0 ~ "In hospital" # will be excluded
    )
  ) %>%
  select(-c(bmi_value))

rm(data_extract)

# read vaccination data
data_vax <- read_rds(here("output", "initial", "eligible", "data_vax.rds")) 

# process vaccination data
data_vax_processed <- data_processed %>%
  select(patient_id, index_date) %>%
  # join long vaccination data
  left_join(
    data_vax %>%
      select(patient_id, matches("vax_\\w+")) %>%
      pivot_longer(
        cols = -patient_id,
        names_pattern = "vax_(.+)_(.+)",
        names_to = c("course", ".value"),
        values_drop_na = TRUE
      )
    , by = "patient_id"
    ) %>%
  # only keep doses on or prior to index date
  filter(date <= index_date) %>%
  group_by(patient_id) %>%
  mutate(
    # flag if undefined dose between study_dates$boosterautumn$ages*  and index_date (inclusive)
    # (those with an undefined dose before study_dates$boosterautumn$ages* have already been dropped)
    undefineddose = "undefined" %in% course
  ) %>%
  ungroup() %>%
  # remove patients with undefined dose 
  filter(!undefineddose) %>% 
  # remove doses on the index date
  filter(date < index_date) %>%
  group_by(patient_id) %>%
  arrange(date, .by_group = TRUE) %>%
  summarise(
    # date of last vaccine dose
    lastvaxbeforeindex_date = last(date),
    # number of doses prior to index
    # dosesbeforeindex_n = n() + 1 # +1 because only one line for primary course
    .groups = "drop"
  ) %>%
  left_join(
    data_vax %>% 
      select(
        patient_id, 
        matches("vax_(primary|boostfirst|boostspring|boostautumn)_(date|brand)")
        ),
    by = "patient_id"
  ) %>%
  mutate(across(matches("boost\\w+_brand"), ~replace_na(.x, "unboosted")))

# join to data_processed
data_processed <- data_processed %>%
  select(-any_of("vax_boostautumn_date")) %>% # as it's in data_vax_processed
  left_join(data_vax_processed, by = "patient_id") %>%
  left_join(
    data_vax %>% select(patient_id, flu_vaccine),
    by = "patient_id"
    )

rm(data_vax, data_vax_processed)

# summarise processed data
my_skim(
  data_processed,
  path = file.path(path_stem, "process", "data_processed_skim.txt")
  )

####################################################################################
# Define selection criteria ----

# apply eligibility crtieria
data_criteria <- data_processed %>%
  transmute(
    
    patient_id,
    registered,
    hasnot_died = !has_died,
    has_follow_up_previous_1year,
    over50 = age >= 50,
    # all vaccine variables will be missing for patients with an undefineddose
    # as such patients were dropped from data_vax_processed, 
    # so use primary_brand to flag
    no_undefineddose = !is.na(vax_primary_brand), 
    lastdoseinterval = !is.na(lastvaxbeforeindex_date) & (as.integer(index_date - lastvaxbeforeindex_date) >= 91),
    has_sex = !is.na(sex),
    has_imd = !is.na(imd_Q5),
    has_ethnicity = !is.na(ethnicity),
    has_region = !is.na(region),
    isnot_carehomeresident = !carehome,
    isnot_hscworker = !hscworker,
    isnot_endoflife = !endoflife,
    isnot_housebound = !housebound,
    isnot_inhospital = !inhospital,
    
    # better to have the c*_descr next to the c* definition here, to ensure both updated following changes
    # quite inefficient though in terms of memory, so encode as factors
    c00_descr = factor("Satisfying initial eligibility criteria"), 
    c00 = TRUE, 
    
    c01_descr = factor("  Died before index date"),
    c01 = c00 & hasnot_died,
    
    c02_descr = factor("  Deregistered before index date"),
    c02 = c01 & registered,
    
    c03_descr = factor("  Registered with a TPP practice for less than one year"), 
    c03 = c02 & has_follow_up_previous_1year,
    
    c04_descr = factor("  Did not turn 50 before index date"),
    c04 = c03 & over50,
    
    c05_descr = factor("  Undefined dose between studystart and index date"),
    c05 = c04 & no_undefineddose,
    
    c06_descr = factor("  Less than 3 months (91 days) since most recent vaccine dose"),
    c06 = c05 & lastdoseinterval,
    
    c07_descr = factor("  Missing sex, IMD, ethnicity, geographical region"),
    c07 = c06 & has_sex & has_imd & has_ethnicity & has_region,
    
    c08_descr = factor("  Care home residents, where known"),
    c08 = c07 & isnot_carehomeresident,
    
    c09_descr = factor("  Health care workers, where known"),
    c09 = c08 & isnot_hscworker,
    
    c10_descr = factor("  People who are considered to be near death, for example on palliative care pathways"),
    c10 = c09 & isnot_endoflife,
    
    c11_descr = factor("  People who are housebound, where known"),
    c11 = c10 & isnot_housebound,
    
    c12_descr = factor("  People who are in hospital"),
    c12 = c11 & isnot_inhospital,
    
    c13_descr = factor("  People who had an unplanned hospital admission with covid-19 and were discharged in the past 1-30 days"),
    c13 = c12 & !(timesincecoviddischarged %in% c("In hospital", "1-30 days")),
    
    include = c13
    
  )

data_eligible <- data_criteria %>%
  filter(include) %>%
  select(patient_id) %>%
  left_join(
    data_processed %>% select(-index_date), #  maybe select specific variables to keep??
    by="patient_id"
    ) %>%
  droplevels()

rm(data_processed)

# save data_eligible ----
my_skim(
  data_eligible,
  path = file.path(path_stem, "eligible", "data_eligible_skim.txt")
)

if (stage %in% c("treated", "controlpotential")) {
  
  write_rds(
    data_eligible,
    file.path(path_stem, "eligible", glue("data_{stage}.rds")),
    compress="gz"
  )
  
}

if (stage == "treated") {
  
  write_csv(
    data_eligible %>% select(patient_id, vax_boostautumn_date),
    file.path(path_stem, "eligible", "data_treated.csv.gz")
  )
  
} 

# create flowchart (only when stage="treated") ----
if (stage == "treated") {
  
  data_flowchart <- data_criteria %>%
    select(patient_id, matches("^c\\d+")) %>%
    rename_at(vars(matches("^c\\d+$")), ~str_c(., "_value")) %>%
    pivot_longer(
      cols = matches("^c\\d+"),
      names_to = c("crit", ".value"),
      names_pattern = "(.*)_(.*)"
    ) %>%
    group_by(crit, descr) %>%
    summarise(n = sum(value), .groups = "keep") %>%
    ungroup() %>%
    rename(criteria = descr) %>%
    arrange(crit) %>%
    mutate(across(criteria, ~if_else(crit == "c00", str_c(criteria, " and boosted"), as.character(.x)))) %>%
    flow_stats_rounded(1)
  
  data_flowchart %>%
    write_csv(
      file.path(path_stem, "flowchart", "flowchart_unrounded.csv")
      )
  
  # combine initial and treated flowcharts 
  # apply midpoint rounding
  # save for release
  read_csv(here("output", "initial", "flowchart", "flowchart_unrounded.csv")) %>%
    mutate(stage = "initial") %>%
    bind_rows(data_flowchart %>% mutate(stage = "treated")) %>%
    group_by(stage) %>%
    flow_stats_rounded(to = threshold) %>%
    ungroup() %>%
    select(stage, crit, criteria, n, everything()) %>%
    write_csv(ghere("output", "report", "flowchart_combined_midpoint{threshold}.csv"))
  
}

# check match (only when stage="actual") ----
if (stage == "controlactual") { 
  
  data_control <- data_eligible
  
  data_treated <- read_rds(ghere("output", "treated", "eligible", "data_treated.rds")) 
  
  data_treated <- 
    left_join(
      data_potential_matchstatus %>% filter(treated==1L),
      data_treated %>% 
        # only keep variables that are in data_control
        select(any_of(names(data_control))),
      by="patient_id"
    )
  
  match_candidates <- 
    bind_rows(data_treated, data_control) %>%
    arrange(treated, match_id, trial_date)
  
  #print missing values
  match_candidates_missing <- map(match_candidates, ~any(is.na(.x)))
  sort(names(match_candidates_missing[unlist(match_candidates_missing)]))
  
  # rematch ----
  rematch <-
    # first join on exact variables + match_id + trial_date
    inner_join(
      x=data_treated %>% select(match_id, trial_date, all_of(c(names(caliper_variables), exact_variables_incremental))),
      y=data_control %>% select(match_id, trial_date, all_of(c(names(caliper_variables), exact_variables_incremental))),
      by = c("match_id", "trial_date", exact_variables_incremental)
    ) 
  
  
  if (length(caliper_variables) > 0) {
    
    # check caliper_variables are still within caliper
    rematch <- rematch %>%
      bind_cols(
        map_dfr(
          set_names(names(caliper_variables), names(caliper_variables)),
          ~ abs(rematch[[str_c(.x, ".x")]] - rematch[[str_c(.x, ".y")]]) <= caliper_variables[.x]
        )
      ) %>%
      # dplyr::if_all not in opensafely version of dplyr so use filter_at instead
      # filter(if_all(
      #   all_of(names(caliper_variables))
      # )) 
      filter_at(
        all_of(names(caliper_variables)),
        all_vars(.)
      )
    
  } 
  
  rematch <- rematch %>%
    select(match_id, trial_date) %>%
    mutate(matched=1)
  
  data_successful_match <-
    match_candidates %>%
    inner_join(rematch, by=c("match_id", "trial_date", "matched")) %>%
    mutate(
      match_round = match_round
    ) %>%
    arrange(trial_date, match_id, treated)
  
  ###
  
  matchstatus_vars <- c("patient_id", "match_id", "trial_date", "match_round", "treated", "controlistreated_date")
  
  data_successful_matchstatus <- data_successful_match %>% 
    # keep all variables from the processed data as they are required for adjustments in the cox model
    select(all_of(matchstatus_vars), everything())
  
  ## size of dataset
  print("data_successful_match treated/untreated numbers")
  table(treated = data_successful_matchstatus$treated, useNA="ifany")
  
  ## how many matches are lost?
  print(glue(
    "{sum(data_successful_matchstatus$treated)} matched-pairs kept out of {sum(data_potential_matchstatus$treated)} 
  ({round(100*(sum(data_successful_matchstatus$treated) / sum(data_potential_matchstatus$treated)),2)}%)"
  ))
  
  ## pick up all previous successful matches ----
  
  if (match_round > 1) {
    
    data_matchstatusprevious <- read_rds(
      ghere("output", "incremental_{match_strategy}", "matchround{match_round-1}", "controlactual", "match", "data_matchstatus_allrounds.rds")
    )
    
    data_matchstatus_allrounds <- 
      data_successful_matchstatus %>% 
      select(all_of(matchstatus_vars)) %>%
      bind_rows(data_matchstatusprevious) 
    
  } else {
    
    data_matchstatus_allrounds <- 
      data_successful_matchstatus %>%
      select(all_of(matchstatus_vars))
    
  }
  
  # save all successful matches
  data_matchstatus_allrounds %>%
    write_rds(
      file.path(path_stem, "match", "data_matchstatus_allrounds.rds"), 
      compress="gz"
      )
  
  if (match_round == n_match_rounds) {
    
    #create directory
    tmp_dir <- here("output", "incremental", "match")
    fs::dir_create(tmp_dir)
    # save patient_id and trial_date for reading into outcome study def
    data_matchstatus_allrounds %>%
      select(patient_id, trial_date) %>%
      write_csv(file.path(tmp_dir, "data_matchcontrol.csv.gz"))
    rm(tmp_dir)
  }
  
  ## size of dataset
  print("data_matchstatus_allrounds treated/untreated numbers")
  table(treated = data_matchstatus_allrounds$treated, useNA="ifany")
  
  ## duplicate IDs
  data_matchstatus_allrounds %>% group_by(treated, patient_id) %>%
    summarise(n=n()) %>% group_by(treated) %>% summarise(ndups = sum(n>1)) %>%
    print()
  
  data_eligible %>%
    my_skim(
      path = file.path(path_stem, "match", "data_successful_matchedcontrols_skim.txt")
      )
  
  data_successful_matchstatus %>% 
    filter(treated==0L) %>% 
    select(-starts_with("vax_boostautumn")) %>%
    write_rds(
      file.path(path_stem, "match", "data_successful_matchedcontrols.rds"), 
      compress="gz"
      )
  
  ## size of dataset
  print("data_successful_match treated/untreated numbers")
  table(treated = data_successful_matchstatus$treated, useNA="ifany")
  
}

