######################################

# This script:

######################################

# Preliminaries ----

## Import libraries ----
library(tidyverse)
library(lubridate)
library(glue)
library(here)

## import local functions and parameters ---

source(here("analysis", "design.R"))

source(here("lib", "functions", "utility.R"))

source(here("analysis", "process", "process_functions.R"))

## import command-line arguments ----

args <- commandArgs(trailingOnly = TRUE)

if (length(args) == 0) {
  # use for interactive testing
  stage <- "treated"
  # stage <- "controlpotential"
  # stage <- "controlactual"
  # stage <- "controlfinal"
  matching_round <- as.integer("1")
} else {
  stage <- args[[1]]
  if (stage %in% "treated") {
    if (length(args) > 1) 
      stop("No additional args to be specified when `stage=\"treated\"")
  } else {
    if (length(args) == 1) {
      stop("`matching_round` must be specified when `stage=\"controlpotential\"` or \"controlactual\"")
    }
    matching_round <- as.integer(args[[2]]) # NULL if treated    
  } 
} 

# ## create output directories and define parameters ----
if (stage == "treated") {
  path_stem <- here("output", "treated")
  fs::dir_create(file.path(path_stem, "flowchart"))
  custom_path <- file.path(path_stem, "dummydata", "dummydata_treated.feather")
} else if (stage %in% c("controlpotential", "controlactual")) {
  path_stem <- ghere("output", "matchround{matching_round}", stage)
  fs::dir_create(file.path(path_stem, "matching"))
  custom_path <- here("output", "matchround1", "controlpotential", "dummydata", "dummydata_controlpotential.feather")
  matching_round_date <- study_dates$control_extract[matching_round]
}
fs::dir_create(file.path(path_stem, "eligible"))
fs::dir_create(file.path(path_stem, "process"))


# import data ----
# read data generated by study def
data_studydef <- arrow::read_feather(
  file.path(path_stem, "extract", glue("input_{stage}.feather"))
) %>%
  process_input()

if (stage == "controlactual") {
  
  ## trial info for potential matches in round X
  data_potential_matchstatus <- 
    read_rds(
      ghere("output", "matchround{matching_round}", "controlpotential", "matching", "data_potential_matchstatus.rds")
      ) %>% 
    filter(matched==1L)
  
}

if(Sys.getenv("OPENSAFELY_BACKEND") %in% c("", "expectations")) {
  
  data_dummy <- arrow::read_feather(custom_path) 
  
  # extra processing if stage=controlactual
  if (stage == "controlactual") {
    
    # set seed so that dummy data results are reproducible
    set.seed(10)
    
    # reuse previous extraction for dummy run, dummy_control_potential1.feather
    data_dummy <- data_dummy %>%
      filter(patient_id %in% data_potential_matchstatus[(data_potential_matchstatus$treated==0L),]$patient_id) %>%
      # trial_date and match_id are not included in the dummy data so join them on here
      # they're joined in the study def using `with_values_from_file`
      left_join(
        data_potential_matchstatus %>% 
          filter(treated==0L) %>%
          select(patient_id, trial_date, match_id),
        by="patient_id"
      ) %>%
      # change a few variables so some matches fail
      mutate(
        region = if_else(runif(n())<0.05, sample(x=unique(region), size=n(), replace=TRUE), region)
      )
    
  }
  
  # check dummydata
  source(here("analysis", "dummydata", "dummydata_check.R"))
  dummydata_check(
    dummydata_studydef= data_studydef,
    dummydata_custom = data_dummy
  )
  
  data_extract <- data_dummy
  rm(data_dummy)
  
} else {
  
  data_extract <- data_studydef
  rm(data_studydef)
  
}


# add certain matching variables
if (stage == "controlactual") {
  
  # add: treated 
  data_extract <- data_extract %>%
    mutate(treated=0L) %>%
    # add: trial_time, matched, control, controlistreated_date to data_extract
    left_join(
      data_potential_matchstatus %>%
        filter(treated==0L),
      by=c("patient_id", "treated", "trial_date", "match_id")
    )
  
}
    
# summarise extracted data 
my_skim(data_extract, path = file.path(path_stem, "extract", glue("input_{stage}_skim.txt")))

# process data -----

# define index_date depending on stage
stage_index_date <- list(
  treated = "vax_boostautumn_date",
  controlpotential = "matching_round_date",
  controlactual = "trial_date"
)

# process variables
data_processed <- data_extract %>%
  mutate(index_date = !! sym(stage_index_date[[stage]]), .after=1) %>%
  select(-any_of(unname(unlist(stage_index_date)))) %>%
  # process jcvi variables
  mutate(
    
    # multimorb =
    #   (sev_obesity) +
    #   (chronic_heart_disease) +
    #   (chronic_kidney_disease) +
    #   (diabetes) +
    #   (chronic_liver_disease) +
    #   (chronic_resp_disease | asthma) +
    #   (chronic_neuro_disease),
    # multimorb = cut(multimorb, breaks = c(0, 1, 2, Inf), labels=c("0", "1", "2+"), right=FALSE),
    # 
    # immunosuppressed = immunosuppressed | asplenia,
    
    # clinically at-risk group
    cv = immunosuppressed | chronic_kidney_disease | chronic_resp_disease |
      asthma | diabetes | chronic_liver_disease | chronic_neuro_disease | 
      chronic_heart_disease | asplenia | learndis | sev_mental,
    
    # these are the agegroups by which people were eligible to book vaccine doses
    # note that technically those aged both 65-74 and 75+ could receive from 12 Sept,
    # but those aged 75+ could book from 7 Sept, whereas 65-74 could only book from 12 Sept
    agegroup_match = cut(
      age,
      breaks=c(50, 65, 75, Inf),
      labels=c("50-64", "65-74", "75+"),
      right=FALSE
    ),
    
  )  %>%
  # process demographics
  mutate(
    
    sex = fct_case_when(
      sex == "F" ~ "Female",
      sex == "M" ~ "Male",
      #sex == "I" ~ "Inter-sex",
      #sex == "U" ~ "Unknown",
      TRUE ~ NA_character_
    ),
    
    ethnicity = factor(
      ethnicity,
      levels = c("White", "Mixed", "Asian or Asian British", "Black or Black British", "Other")
    ),
    
    region = fct_collapse(
      region,
      `East of England` = "East",
      `London` = "London",
      `Midlands` = c("West Midlands", "East Midlands"),
      `North East and Yorkshire` = c("Yorkshire and The Humber", "North East"),
      `North West` = "North West",
      `South East` = "South East",
      `South West` = "South West"
    ),
    
    imd_Q5 = factor(
      imd_Q5,
      levels = c("1 (most deprived)", "2", "3", "4", "5 (least deprived)")
    )
    
  ) 

# tidy up
rm(data_extract)

# read vaccination data
data_vax <- read_rds(here("output", "initial", "eligible", "data_vax.rds")) 

# process vaccination data
data_vax_processed <- data_processed %>%
  select(patient_id, index_date) %>%
  # join long vaccination data
  left_join(
    data_vax %>%
      select(patient_id, matches("vax_\\w+")) %>%
      pivot_longer(
        cols = -patient_id,
        names_pattern = "vax_(.+)_(.+)",
        names_to = c("course", ".value"),
        values_drop_na = TRUE
      )
    , by = "patient_id"
    ) %>%
  # only keep doses on or prior to index date
  filter(date <= index_date) %>%
  group_by(patient_id) %>%
  mutate(
    # flag if undefined dose between study_dates$boosterautumn$ages*  and index_date (inclusive)
    # (those with an undefined dose before study_dates$boosterautumn$ages* have already been dropped)
    undefineddose = "undefined" %in% course
  ) %>%
  ungroup() %>%
  # remove patients with undefined dose 
  filter(!undefineddose) %>% 
  # remove doses on the index date
  filter(date < index_date) %>%
  group_by(patient_id) %>%
  arrange(date, .by_group = TRUE) %>%
  summarise(
    # date of last vaccine dose
    lastvaxbeforeindex_date = last(date),
    # number of doses prior to index
    # dosesbeforeindex_n = n() + 1 # +1 because only one line for primary course
  ) %>%
  ungroup() %>%
  left_join(
    data_vax %>% 
      select(
        patient_id, 
        matches("vax_(primary|boostfirst|boostspring|boostautumn)_(date|brand)")
        ),
    by = "patient_id"
  ) %>%
  mutate(across(matches("boost\\w+_brand"), ~replace_na(.x, "unboosted")))

# join to data_processed
data_processed <- data_processed %>%
  left_join(data_vax_processed, by = "patient_id")

# tidy up
rm(data_vax, data_vax_processed)

# summarise processed data
my_skim(
  data_processed,
  path = file.path(path_stem, "process", "data_processed_skim.txt")
  )

####################################################################################
# Define selection criteria ----

# apply eligibility crtieria
data_criteria <- data_processed %>%
  transmute(
    
    patient_id,
    has_follow_up_previous_1year,
    # all vaccine variables will be missing for patients with an undefineddose
    # as such patients were dropped from data_vax_processed, 
    # just use primary_brand to flag
    no_undefineddose = !is.na(vax_primary_brand), 
    lastdoseinterval = !is.na(lastvaxbeforeindex_date) & (as.integer(index_date - lastvaxbeforeindex_date) >= 91),
    has_sex = !is.na(sex),
    has_imd = !is.na(imd_Q5),
    has_ethnicity = !is.na(ethnicity),
    has_region = !is.na(region),
    isnot_carehomeresident = !carehome,
    isnot_hscworker = !hscworker,
    isnot_endoflife = !endoflife,
    isnot_housebound = !housebound,
    isnot_inhospital = case_when(
      is.na(admitted_unplanned_0_date) ~ TRUE,
      !is.na(discharged_unplanned_0_date) & (discharged_unplanned_0_date < index_date) ~ TRUE,
      TRUE ~ FALSE
    ),
    
    # better to have the c*_descr next to the c* definition here, to ensure both updated following changes
    # quite inefficient though in terms of memory, so encode as factors
    c0_descr = factor("Satisfying initial eligibility criteria"), 
    c0 = TRUE, 
    
    c1_descr = factor("  Registered with a TPP practice for less than one year"), 
    c1 = c0 & has_follow_up_previous_1year,
    
    c2_descr = factor("  Undefined dose between studystart and index date"),
    c2 = c1 & no_undefineddose,
    
    c3_descr = factor("  Less than 3 months (91 days) since most recent vaccine dose"),
    c3 = c2 & lastdoseinterval,
    
    c4_descr = factor("  Missing sex, IMD, ethnicity, geographical region"),
    c4 = c3 & has_sex & has_imd & has_ethnicity & has_region,
    
    c5_descr = factor("  Care home residents, where known"),
    c5 = c4 & isnot_carehomeresident,
    
    c6_descr = factor("  Health care workers, where known"),
    c6 = c5 & isnot_hscworker,
    
    c7_descr = factor("  People who are considered to be near death, for example on palliative care pathways"),
    c7 = c6 & isnot_endoflife,
    
    c8_descr = factor("  People who are housebound, where known"),
    c8 = c7 & isnot_housebound,
    
    c9_descr = factor("  People who are in hospital on an unplanned admission"),
    c9 = c8 & isnot_inhospital,
    
    include = c9
    
  )

data_eligible <- data_criteria %>%
  filter(include) %>%
  select(patient_id) %>%
  left_join(
    data_processed, #  maybe select specific variables to keep??
    by="patient_id"
    ) %>%
  droplevels()


# save data_eligible ----
my_skim(
  data_eligible,
  path = file.path(path_stem, "eligible", "data_eligible_skim.txt")
)

if (stage %in% c("treated", "controlpotential")) {
  
  write_rds(
    data_eligible,
    file.path(path_stem, "eligible", glue("data_{stage}.rds")),
    compress="gz"
  )
  
}

if (stage == "treated") {
  
  write_csv(
    data_eligible %>% select(patient_id, vax_boostautumn_date),
    file.path(path_stem, "eligible", "data_treated.csv.gz")
  )
  
} 

# create flowchart (only when stage="treated") ----
if (stage == "treated") {
  
  data_flowchart <- data_criteria %>%
    select(patient_id, matches("^c\\d")) %>%
    rename_at(vars(matches("^c\\d$")), ~str_c(., "_value")) %>%
    pivot_longer(
      cols = matches("^c\\d"),
      names_to = c("crit", ".value"),
      names_pattern = "(.*)_(.*)"
    ) %>%
    group_by(crit, descr) %>%
    summarise(n = sum(value), .groups = "keep") %>%
    ungroup() %>%
    rename(criteria = descr) %>%
    arrange(crit) %>%
    flow_stats_rounded(1)
  
  data_flowchart %>%
    write_csv(
      file.path(path_stem, "flowchart", "flowchart_unrounded.csv")
      )
  
}

# check matching (only when stage="actual") ----
if (stage == "controlactual") { 
  
  data_control <- data_eligible
  
  data_treated <- read_rds(ghere("output", "treated", "eligible", "data_treated.rds")) 
  
  data_treated <- 
    left_join(
      data_potential_matchstatus %>% filter(treated==1L),
      data_treated %>% 
        # only keep variables that are in data_control
        select(any_of(names(data_control))),
      by="patient_id"
    )
  
  matching_candidates <- 
    bind_rows(data_treated, data_control) %>%
    arrange(treated, match_id, trial_date)
  
  #print missing values
  matching_candidates_missing <- map(matching_candidates, ~any(is.na(.x)))
  sort(names(matching_candidates_missing[unlist(matching_candidates_missing)]))
  
  # rematch ----
  rematch <-
    # first join on exact variables + match_id + trial_date
    inner_join(
      x=data_treated %>% select(match_id, trial_date, all_of(c(names(caliper_variables), exact_variables))),
      y=data_control %>% select(match_id, trial_date, all_of(c(names(caliper_variables), exact_variables))),
      by = c("match_id", "trial_date", exact_variables)
    ) 
  
  
  if (length(caliper_variables) > 0) {
    
    # check caliper_variables are still within caliper
    rematch <- rematch %>%
      bind_cols(
        map_dfr(
          set_names(names(caliper_variables), names(caliper_variables)),
          ~ abs(rematch[[str_c(.x, ".x")]] - rematch[[str_c(.x, ".y")]]) <= caliper_variables[.x]
        )
      ) %>%
      # dplyr::if_all not in opensafely version of dplyr so use filter_at instead
      # filter(if_all(
      #   all_of(names(caliper_variables))
      # )) 
      filter_at(
        all_of(names(caliper_variables)),
        all_vars(.)
      )
    
  } 
  
  rematch <- rematch %>%
    select(match_id, trial_date) %>%
    mutate(matched=1)
  
  data_successful_match <-
    matching_candidates %>%
    inner_join(rematch, by=c("match_id", "trial_date", "matched")) %>%
    mutate(
      matching_round = matching_round
    ) %>%
    arrange(trial_date, match_id, treated)
  
  ###
  
  matchstatus_vars <- c("patient_id", "match_id", "trial_date", "matching_round", "treated", "controlistreated_date")
  
  data_successful_matchstatus <- data_successful_match %>% 
    # keep all variables from the processed data as they are required for adjustments in the cox model
    select(all_of(matchstatus_vars), everything())
  
  ## size of dataset
  print("data_successful_match treated/untreated numbers")
  table(treated = data_successful_matchstatus$treated, useNA="ifany")
  
  ## how many matches are lost?
  print(glue(
    "{sum(data_successful_matchstatus$treated)} matched-pairs kept out of {sum(data_potential_matchstatus$treated)} 
  ({round(100*(sum(data_successful_matchstatus$treated) / sum(data_potential_matchstatus$treated)),2)}%)"
  ))
  
  ## pick up all previous successful matches ----
  
  if (matching_round > 1) {
    
    data_matchstatusprevious <- read_rds(
      ghere("output", "matchround{matching_round-1}", "controlactual", "matching", "data_matchstatus_allrounds.rds")
    )
    
    data_matchstatus_allrounds <- 
      data_successful_matchstatus %>% 
      select(all_of(matchstatus_vars)) %>%
      bind_rows(data_matchstatusprevious) 
    
  } else {
    
    data_matchstatus_allrounds <- 
      data_successful_matchstatus %>%
      select(all_of(matchstatus_vars))
    
  }
  
  # save all successful matches
  data_matchstatus_allrounds %>%
    write_rds(
      file.path(path_stem, "matching", "data_matchstatus_allrounds.rds"), 
      compress="gz"
      )
  
  # # output all included patient ids for final study definition
  # if (matching_round == n_matching_rounds) {
  #   
  #   fs::dir_create(here("output", "final", "eligible"))
  #   
  #   # save ids for reading into final study definition
  #   bind_rows(
  #     data_treated,
  #     data_matchstatus_allrounds
  #   ) %>% 
  #     select(patient_id, trial_date, match_id) %>%
  #     mutate(across(trial_date, as.character)) %>%
  #     write_csv(
  #       here("output", "final", "eligible", "ids_final.csv.gz")
  #     )
  #   
  # }
  
  ## size of dataset
  print("data_matchstatus_allrounds treated/untreated numbers")
  table(treated = data_matchstatus_allrounds$treated, useNA="ifany")
  
  ## duplicate IDs
  data_matchstatus_allrounds %>% group_by(treated, patient_id) %>%
    summarise(n=n()) %>% group_by(treated) %>% summarise(ndups = sum(n>1)) %>%
    print()
  
  data_eligible %>%
    my_skim(
      path = file.path(path_stem, "matching", "data_successful_matchedcontrols_skim.txt")
      )
  data_successful_matchstatus %>% 
    filter(treated==0L) %>% 
    write_rds(
      file.path(path_stem, "matching", "data_successful_matchedcontrols.rds"), 
      compress="gz"
      )
  
  ## size of dataset
  print("data_successful_match treated/untreated numbers")
  table(treated = data_successful_matchstatus$treated, useNA="ifany")
  
}
